# Generated by Django 3.1.2 on 2020-10-10 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0003_auto_20201010_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='header',
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default='', max_length=100, verbose_name='Asunto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='creationDateTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 10, 19, 15, 52, 341844), verbose_name='Fecha de creación de la cita'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sendDateTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 10, 19, 15, 52, 341844), verbose_name='Fecha de envío del comentario'),
        ),
    ]
