# Generated by Django 3.1.2 on 2020-10-11 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0007_auto_20201011_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='appointments', related_query_name='appointment', to=settings.AUTH_USER_MODEL),
        ),
    ]
