# Generated by Django 3.1.2 on 2020-10-10 18:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Mensaje')),
                ('header', models.CharField(max_length=100, verbose_name='Cabecera')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('sendDateTime', models.DateTimeField(default=datetime.datetime(2020, 10, 10, 19, 4, 16, 530720), verbose_name='Fecha de envío del comentario')),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='creationDateTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 10, 19, 4, 16, 530720), verbose_name='Fecha de creación de la cita'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
