# Generated by Django 3.1.2 on 2020-10-10 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0002_auto_20201010_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='creationDateTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 10, 19, 12, 22, 11211), verbose_name='Fecha de creación de la cita'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sendDateTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 10, 19, 12, 22, 11211), verbose_name='Fecha de envío del comentario'),
        ),
    ]
