# Generated by Django 3.1.2 on 2020-10-11 13:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0004_auto_20201010_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='creationDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación de la cita'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sendDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de envío del comentario'),
        ),
    ]
