# Generated by Django 3.1.2 on 2020-10-11 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0006_auto_20201011_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='bookingDateTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de la reserva'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='creationDateTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Fecha de creación de la cita'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
    ]
